// <auto-generated />
namespace DutchHearts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201604172359 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201604172359));
        
        string IMigrationMetadata.Id
        {
            get { return "201604172159475_201604172359"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
